sylius_academy.workshop_plugin.admin_brand:
    resource: |
        alias: sylius_academy_workshop.brand
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        except: ['show']
        grid: sylius_academy.workshop_plugin.admin_brand
        vars:
            all:
                templates:
                    form: '@SyliusAcademyWorkshopPlugin/Admin/Brand/_form.html.twig'
    type: sylius.resource

sylius_academy.workshop_plugin.admin_brand_show:
    path: /brands/{id}
    methods: [GET]
    defaults:
        _controller: sylius_academy_workshop.controller.brand::showAction
        _sylius:
            template: "@SyliusAcademyWorkshopPlugin/Admin/Brand/show.html.twig"

sylius_academy.workshop_plugin.admin_brand_approve:
    path: /brands/{id}/approve
    methods: [PUT]
    defaults:
        _controller: sylius_academy_workshop.controller.brand::applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: sylius_brand
                transition: approve
            redirect: referer

sylius_academy.workshop_plugin.admin_brand_reject:
    path: /brands/{id}/reject
    methods: [PUT]
    defaults:
        _controller: sylius_academy_workshop.controller.brand::applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: sylius_brand
                transition: reject
            redirect: referer

sylius_academy.workshop_plugin.admin_brand_suspend:
    path: /brands/{id}/suspend
    methods: [PUT]
    defaults:
        _controller: sylius_academy_workshop.controller.brand::applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: sylius_brand
                transition: suspend
            redirect: referer
