imports:
    - { resource: "@SyliusAcademyWorkshopPlugin/config/grids/*.yaml" }
    - { resource: "@SyliusAcademyWorkshopPlugin/config/workflow/*.yaml" }
    - { resource: "@SyliusAcademyWorkshopPlugin/config/fixtures/*.yaml" }
